### PR TITLE
#12: added generics for parameter class of service

### PR DESCRIPTION
**Pull request by gossie**
The imports were rearranged by eclipse, sorry!

### CODE REVIEW

**Comment by gossie** [comment]
The tests are green but the deployment failed.

**Comment by saschalamp** [comment]
Deployment fails because of hidden credentials for Maven Central. This issue has just been fixed on the master branch. Travis won't deploy pull requests anymore.

**Comment by gossie** [comment]
Green!

**Comment by saschalamp** [comment]
Thank you for your contribution:)

**Pull request merged**
